#!/usr/bin/env bash
# Install HAproxy and configure it to send
# traffic between first and second servers using roundrobin algorithm
sudo apt-get update -y
sudo apt-get install haproxy -y

# Configuring HAproxy
sudo tee /etc/haproxy/haproxy.cfg > dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
   bind *:80
   default_backend http_back

backend http_back
   balance roundrobin
   server 199809-web-01 34.229.137.94:80 check
   server 199809-web-02 52.26.246.233:80 check
EOT

# Test HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo systemctl start haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
