#!/usr/bin/env bash
#A bash script that created the file /var/run/myscript.pid containing its PID.
# It displays to infinity and beyond indefinitely
#It displays "I hate the kill command" when receiving a SIGTERM signal
#It displays "Y U no love me?!" when receiving a SIGINT signal
#It deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT 
#or SIGNAL signal


sudo touch /var/run/myscript.pid
sudo chmod +x /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

trap "echo I hate the kill command; sudo rm /var/run/myscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm /var/run/myscript.pid" SIGQUIT

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
