#!/usr/bin/env bash
# a bash script that displays "To infinity and beyond" indefinitely
# it has a "sleep 2" in between each iteration
# it displays "I am inviscible" when receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM

while 'true'
do
	echo "To infinity and beyond"
	sleep 2
done
