#!/usr/bin/bash env
#a Bash script that displays the content of the file /etc/passwd
#the script only displays username, user, id, Home directory path for the user
k=0
while [ $k -lt 2 ]
do
	cut -d ":" -f 1,3,6 /etc/passwd
	((k++))
done
