#!/usr/bin/env bash
#a Bash script that loops from 1 to 10 and
# displays bad luck for the 4rth loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
k=1
while (("$k" < 10))
do
	if [ "$k" == 4 ]
	then
		echo "bad luck"
	elif [ "$k" == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((k++))
done 
