#!/usr/bin/env bash
# Fix a web server to run Nginx as the nginx on port 8080.

# replace '#user'
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replace port 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# give read and write permissions
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill the process if it is running
# pkill apache2

# now start the nginx service with the new nginx user
sudo -u nginx service nginx start
